services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: graphs
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata: